export const questionData = [
  {
    userId: 1,
    id: 1,
    question: "bell ",
    trueAnswer: "zil",
    falseAnswer: "inanmak",
  },
  {
    userId: 1,
    id: 2,
    question: "beside ",
    trueAnswer: "yanında",
    falseAnswer: "arasında",
  },
  {
    userId: 1,
    id: 3,
    question: "blood  ",
    trueAnswer: "kan",
    falseAnswer: "doğmuş",
  },
  {
    userId: 1,
    id: 4,
    question: "carry  ",
    trueAnswer: "taşımak",
    falseAnswer: "hücre",
  },
  {
    userId: 1,
    id: 5,
    question: "chance  ",
    trueAnswer: "şans",
    falseAnswer: "değişmek",
  },
  {
    userId: 1,
    id: 6,
    question: "church  ",
    trueAnswer: "kilise",
    falseAnswer: "çember",
  },
  {
    userId: 1,
    id: 7,
    question: "climb",
    trueAnswer: "tırmanmak",
    falseAnswer: "ortak",
  },
  {
    userId: 1,
    id: 8,
    question: "cost  ",
    trueAnswer: "masraf",
    falseAnswer: "saymak",
  },
  {
    userId: 1,
    id: 9,
    question: "cross  ",
    trueAnswer: "mevcut",
    falseAnswer: "anlaşma",
  },
  {
    userId: 1,
    id: 10,
    question: "determine  ",
    trueAnswer: "belirlemek",
    falseAnswer: "sözlük",
  },
  {
    userId: 1,
    id: 11,
    question: "distance  ",
    trueAnswer: "mesafe",
    falseAnswer: "kapı",
  },
  {
    userId: 1,
    id: 12,
    question: "entire  ",
    trueAnswer: "tüm",
    falseAnswer: "inanmak",
  },
  {
    userId: 1,
    id: 13,
    question: "grass  ",
    trueAnswer: "çimen",
    falseAnswer: "yeşil",
  },
  {
    userId: 1,
    id: 14,
    question: "gun  ",
    trueAnswer: "silah",
    falseAnswer: "zemin",
  },
];
